import { animations } from "@tamagui/config/v5-reanimated";
import {
  createSystemFont,
  createV5Theme,
  defaultChildrenThemes,
  defaultConfig,
} from "@tamagui/config/v5";
import {
  green,
  greenDark,
  red,
  redDark,
  yellow,
  yellowDark,
} from "@tamagui/colors";
import { v5ComponentThemes } from "@tamagui/themes/v5";
import { createTamagui } from "tamagui";
import { fintPalette } from "./src/theme/palette";

const darkPalette = [
  fintPalette.dark.surface,
  fintPalette.dark.background,
  fintPalette.dark.subtle,
  fintPalette.dark.elevated,
  fintPalette.dark.border,
  fintPalette.dark.border,
  fintPalette.dark.muted,
  fintPalette.dark.muted,
  fintPalette.dark.muted,
  fintPalette.dark.muted,
  fintPalette.dark.text,
  fintPalette.dark.text,
];

const lightPalette = [
  fintPalette.light.surface,
  fintPalette.light.background,
  fintPalette.light.subtle,
  fintPalette.light.elevated,
  fintPalette.light.border,
  fintPalette.light.border,
  fintPalette.light.muted,
  fintPalette.light.muted,
  fintPalette.light.muted,
  fintPalette.light.muted,
  fintPalette.light.text,
  fintPalette.light.text,
];

const accentLight = {
  accent1: fintPalette.light.background,
  accent2: fintPalette.light.subtle,
  accent3: fintPalette.light.elevated,
  accent4: fintPalette.light.border,
  accent5: fintPalette.light.accent,
  accent6: fintPalette.light.accent,
  accent7: fintPalette.light.primary,
  accent8: fintPalette.light.primary,
  accent9: fintPalette.light.primary,
  accent10: fintPalette.light.primaryStrong,
  accent11: fintPalette.light.primaryStrong,
  accent12: fintPalette.light.text,
};

const accentDark = {
  accent1: fintPalette.dark.background,
  accent2: fintPalette.dark.subtle,
  accent3: fintPalette.dark.elevated,
  accent4: fintPalette.dark.border,
  accent5: fintPalette.dark.primary,
  accent6: fintPalette.dark.primary,
  accent7: fintPalette.dark.primary,
  accent8: fintPalette.dark.primary,
  accent9: fintPalette.dark.primary,
  accent10: fintPalette.dark.primaryStrong,
  accent11: fintPalette.dark.primaryStrong,
  accent12: fintPalette.dark.text,
};

const generatedThemes = createV5Theme({
  darkPalette,
  lightPalette,
  componentThemes: v5ComponentThemes,
  accent: {
    light: accentLight,
    dark: accentDark,
  },
  childrenThemes: {
    ...defaultChildrenThemes,
    warning: {
      light: yellow,
      dark: yellowDark,
    },
    error: {
      light: red,
      dark: redDark,
    },
    success: {
      light: green,
      dark: greenDark,
    },
  },
});

const themes = {
  ...generatedThemes,
  light: {
    ...generatedThemes.light,
    background: fintPalette.light.background,
    color: fintPalette.light.text,
    card: fintPalette.light.surface,
    cardForeground: fintPalette.light.text,
    popover: fintPalette.light.surface,
    popoverForeground: fintPalette.light.text,
    primary: fintPalette.light.action,
    primaryForeground: fintPalette.light.surface,
    primaryStrong: fintPalette.light.actionPressed,
    portfolio: fintPalette.light.action,
    portfolioForeground: fintPalette.light.surface,
    secondary: fintPalette.light.subtle,
    secondaryForeground: fintPalette.light.primaryStrong,
    muted: fintPalette.light.subtle,
    mutedForeground: fintPalette.light.muted,
    elevated: fintPalette.light.elevated,
    accent: fintPalette.light.action,
    accentForeground: fintPalette.light.surface,
    destructive: fintPalette.light.danger,
    success: fintPalette.light.success,
    borderColor: fintPalette.light.border,
    input: fintPalette.light.border,
    ring: fintPalette.light.action,
    accent8: fintPalette.light.action,
    accent9: fintPalette.light.action,
    accent10: fintPalette.light.action,
    headerBackground: fintPalette.light.headerBackground,
    headerBorder: fintPalette.light.headerBorder,
    headerForeground: fintPalette.light.headerText,
    headerMuted: fintPalette.light.headerMuted,
    headerAccent: fintPalette.light.headerAccent,
    tabBackground: fintPalette.light.tabBackground,
    tabBorder: fintPalette.light.tabBorder,
    tabActive: fintPalette.light.tabActive,
    tabInactive: fintPalette.light.tabInactive,
    heroBackground: fintPalette.light.heroBackground,
    heroBorder: fintPalette.light.heroBorder,
    heroForeground: fintPalette.light.surface,
    heroMuted: fintPalette.light.heroMuted,
    heroAccent: fintPalette.light.accent,
    red2: fintPalette.light.subtle,
    red3: fintPalette.light.subtle,
    red6: fintPalette.light.danger,
    red8: fintPalette.light.danger,
    red9: fintPalette.light.danger,
    red10: fintPalette.light.danger,
    red11: fintPalette.light.danger,
    green2: fintPalette.light.subtle,
    green3: fintPalette.light.subtle,
    green6: fintPalette.light.success,
    green9: fintPalette.light.success,
    green10: fintPalette.light.success,
    green11: fintPalette.light.success,
    chart1: fintPalette.light.action,
    chart2: fintPalette.light.accent,
    chart3: fintPalette.light.success,
    chart4: "rgb(245, 158, 11)",
    chart5: fintPalette.light.danger,
  },
  dark: {
    ...generatedThemes.dark,
    background: fintPalette.dark.background,
    color: fintPalette.dark.text,
    card: fintPalette.dark.surface,
    cardForeground: fintPalette.dark.text,
    popover: fintPalette.dark.surface,
    popoverForeground: fintPalette.dark.text,
    primary: fintPalette.dark.action,
    primaryForeground: fintPalette.dark.background,
    primaryStrong: fintPalette.dark.actionPressed,
    portfolio: fintPalette.dark.action,
    portfolioForeground: fintPalette.dark.background,
    secondary: fintPalette.dark.subtle,
    secondaryForeground: fintPalette.dark.primaryStrong,
    muted: fintPalette.dark.subtle,
    mutedForeground: fintPalette.dark.muted,
    elevated: fintPalette.dark.elevated,
    accent: fintPalette.dark.action,
    accentForeground: fintPalette.dark.background,
    destructive: fintPalette.dark.danger,
    success: fintPalette.dark.success,
    borderColor: fintPalette.dark.border,
    input: fintPalette.dark.border,
    ring: fintPalette.dark.action,
    accent8: fintPalette.dark.action,
    accent9: fintPalette.dark.action,
    accent10: fintPalette.dark.action,
    headerBackground: fintPalette.dark.headerBackground,
    headerBorder: fintPalette.dark.headerBorder,
    headerForeground: fintPalette.dark.headerText,
    headerMuted: fintPalette.dark.headerMuted,
    headerAccent: fintPalette.dark.headerAccent,
    tabBackground: fintPalette.dark.tabBackground,
    tabBorder: fintPalette.dark.tabBorder,
    tabActive: fintPalette.dark.tabActive,
    tabInactive: fintPalette.dark.tabInactive,
    heroBackground: fintPalette.dark.heroBackground,
    heroBorder: fintPalette.dark.heroBorder,
    heroForeground: fintPalette.dark.text,
    heroMuted: fintPalette.dark.heroMuted,
    heroAccent: fintPalette.dark.action,
    red2: fintPalette.dark.subtle,
    red3: fintPalette.dark.subtle,
    red6: fintPalette.dark.danger,
    red8: fintPalette.dark.danger,
    red9: fintPalette.dark.danger,
    red10: fintPalette.dark.danger,
    red11: fintPalette.dark.danger,
    green2: fintPalette.dark.subtle,
    green3: fintPalette.dark.subtle,
    green6: fintPalette.dark.success,
    green9: fintPalette.dark.success,
    green10: fintPalette.dark.success,
    green11: fintPalette.dark.success,
    chart1: fintPalette.dark.action,
    chart2: fintPalette.dark.primaryStrong,
    chart3: fintPalette.dark.success,
    chart4: "rgb(251, 191, 36)",
    chart5: fintPalette.dark.danger,
  },
};

const bodyFont = createSystemFont({
  font: {
    family: "Inter",
    face: {
      400: { normal: "InterRegular" },
      500: { normal: "InterMedium" },
      600: { normal: "InterSemiBold" },
      700: { normal: "InterBold" },
    },
    weight: {
      1: "400",
      4: "400",
      5: "500",
      6: "600",
      7: "700",
      8: "700",
      9: "700",
    },
    letterSpacing: {
      1: 0,
      4: -0.05,
      6: -0.1,
      9: -0.2,
    },
  },
});

export const config = createTamagui({
  ...defaultConfig,
  animations,
  fonts: {
    ...defaultConfig.fonts,
    body: bodyFont,
    heading: bodyFont,
  },
  themes,
});

export default config;

export type Conf = typeof config;

declare module "tamagui" {
  interface TamaguiCustomConfig extends Conf {}
}
