import { animations } from "@tamagui/config/v5-reanimated";
import {
  createSystemFont,
  createV5Theme,
  defaultChildrenThemes,
  defaultConfig,
} from "@tamagui/config/v5";
import {
  green,
  greenDark,
  red,
  redDark,
  yellow,
  yellowDark,
} from "@tamagui/colors";
import { v5ComponentThemes } from "@tamagui/themes/v5";
import { createTamagui } from "tamagui";
import { fintPalette } from "./src/theme/palette";
import { fontFace } from "./src/theme/typography";


const darkPalette = [
  fintPalette.dark.surface,
  fintPalette.dark.background,
  fintPalette.dark.subtle,
  fintPalette.dark.elevated,
  fintPalette.dark.border,
  fintPalette.dark.border,
  fintPalette.dark.muted,
  fintPalette.dark.muted,
  fintPalette.dark.muted,
  fintPalette.dark.muted,
  fintPalette.dark.text,
  fintPalette.dark.text,
];

const lightPalette = [
  fintPalette.light.surface,
  fintPalette.light.background,
  fintPalette.light.subtle,
  fintPalette.light.elevated,
  fintPalette.light.border,
  fintPalette.light.border,
  fintPalette.light.muted,
  fintPalette.light.muted,
  fintPalette.light.muted,
  fintPalette.light.muted,
  fintPalette.light.text,
  fintPalette.light.text,
];

const accentLight = {
  accent1: fintPalette.light.background,
  accent2: fintPalette.light.subtle,
  accent3: fintPalette.light.elevated,
  accent4: fintPalette.light.border,
  accent5: fintPalette.light.accent,
  accent6: fintPalette.light.accent,
  accent7: fintPalette.light.primary,
  accent8: fintPalette.light.primary,
  accent9: fintPalette.light.primary,
  accent10: fintPalette.light.primaryStrong,
  accent11: fintPalette.light.primaryStrong,
  accent12: fintPalette.light.text,
};

const accentDark = {
  accent1: fintPalette.dark.background,
  accent2: fintPalette.dark.subtle,
  accent3: fintPalette.dark.elevated,
  accent4: fintPalette.dark.border,
  accent5: fintPalette.dark.primary,
  accent6: fintPalette.dark.primary,
  accent7: fintPalette.dark.primary,
  accent8: fintPalette.dark.primary,
  accent9: fintPalette.dark.primary,
  accent10: fintPalette.dark.primaryStrong,
  accent11: fintPalette.dark.primaryStrong,
  accent12: fintPalette.dark.text,
};

const generatedThemes = createV5Theme({
  darkPalette,
  lightPalette,
  componentThemes: v5ComponentThemes,
  accent: {
    light: accentLight,
    dark: accentDark,
  },
  childrenThemes: {
    ...defaultChildrenThemes,
    warning: {
      light: yellow,
      dark: yellowDark,
    },
    error: {
      light: red,
      dark: redDark,
    },
    success: {
      light: green,
      dark: greenDark,
    },
  },
});

const themes = {
  ...generatedThemes,
  light: {
    ...generatedThemes.light,
    background: fintPalette.light.background,
    color: fintPalette.light.text,
    card: fintPalette.light.surface,
    cardForeground: fintPalette.light.text,
    popover: fintPalette.light.surface,
    popoverForeground: fintPalette.light.text,
    primary: fintPalette.light.action,
    primaryForeground: fintPalette.light.surface,
    primaryStrong: fintPalette.light.actionPressed,
    portfolio: fintPalette.light.action,
    portfolioForeground: fintPalette.light.surface,
    secondary: fintPalette.light.subtle,
    secondaryForeground: fintPalette.light.primaryStrong,
    muted: fintPalette.light.subtle,
    mutedForeground: fintPalette.light.muted,
    elevated: fintPalette.light.elevated,
    accent: fintPalette.light.action,
    accentForeground: fintPalette.light.surface,
    destructive: fintPalette.light.dangerHard,
    success: fintPalette.light.success,
    borderColor: fintPalette.light.border,
    input: fintPalette.light.border,
    ring: fintPalette.light.action,
    accent8: fintPalette.light.action,
    accent9: fintPalette.light.action,
    accent10: fintPalette.light.action,
    headerBackground: fintPalette.light.headerBackground,
    headerBorder: fintPalette.light.headerBorder,
    headerForeground: fintPalette.light.headerText,
    headerMuted: fintPalette.light.headerMuted,
    headerAccent: fintPalette.light.headerAccent,
    tabBackground: fintPalette.light.tabBackground,
    tabBorder: fintPalette.light.tabBorder,
    tabActive: fintPalette.light.tabActive,
    tabInactive: fintPalette.light.tabInactive,
    tabFloatingBackground: fintPalette.light.tabFloatingBackground,
    tabFloatingBorder: fintPalette.light.tabFloatingBorder,
    tabPill: fintPalette.light.tabPill,
    heroBackground: fintPalette.light.heroBackground,
    heroBorder: fintPalette.light.heroBorder,
    heroForeground: fintPalette.light.groundForeground,
    heroMuted: fintPalette.light.heroMuted,
    heroAccent: fintPalette.light.groundAccent,
    // Sistema de diseño: los componentes nuevos de src/ui usan estas claves.
    canvas: fintPalette.light.canvas,
    surface: fintPalette.light.surface,
    surfaceSunken: fintPalette.light.surfaceSunken,
    surfaceOverlay: fintPalette.light.surfaceOverlay,
    segmentThumb: fintPalette.light.segmentThumb,
    slab: fintPalette.light.slab,
    slabLine: fintPalette.light.slabLine,
    line: fintPalette.light.line,
    lineStrong: fintPalette.light.lineStrong,
    ink: fintPalette.light.ink,
    inkMuted: fintPalette.light.inkMuted,
    inkFaint: fintPalette.light.inkFaint,
    slabInk: fintPalette.light.slabInk,
    slabMuted: fintPalette.light.slabMuted,
    brand: fintPalette.light.brand,
    brandStrong: fintPalette.light.brandStrong,
    brandWash: fintPalette.light.brandWash,
    onBrand: fintPalette.light.onBrand,
    focus: fintPalette.light.focus,
    flowIn: fintPalette.light.flowIn,
    flowOut: fintPalette.light.flowOut,
    flowInSlab: fintPalette.light.flowInSlab,
    flowOutSlab: fintPalette.light.flowOutSlab,
    brandSlab: fintPalette.light.brandSlab,
    heroGlow: fintPalette.light.heroGlow,
    heroGlowSoft: fintPalette.light.heroGlowSoft,
    glassSlab: fintPalette.light.glassSlab,
    glassSlabLine: fintPalette.light.glassSlabLine,
    dangerHard: fintPalette.light.dangerHard,
    onDanger: fintPalette.light.onDanger,
    signal: fintPalette.light.signal,
    chartTrack: fintPalette.light.chartTrack,
    scrim: fintPalette.light.scrim,
    glass: fintPalette.light.glass,
    glassLine: fintPalette.light.glassLine,
    chart1: fintPalette.light.chart[0],
    chart2: fintPalette.light.chart[1],
    chart3: fintPalette.light.chart[2],
    chart4: fintPalette.light.chart[3],
    chart5: fintPalette.light.chart[4],
    chart6: fintPalette.light.chart[5],
    red2: fintPalette.light.negativeTint,
    red3: fintPalette.light.negativeTint,
    red4: "#FDD5D1",
    red5: "#F5C5C1",
    red6: fintPalette.light.danger,
    red8: fintPalette.light.danger,
    red9: fintPalette.light.danger,
    red10: fintPalette.light.danger,
    red11: fintPalette.light.danger,
    green2: fintPalette.light.positiveTint,
    green3: fintPalette.light.positiveTint,
    green4: "#C7EBCD",
    green6: fintPalette.light.success,
    green9: fintPalette.light.success,
    green10: fintPalette.light.success,
    green11: fintPalette.light.success,
    yellow2: "#FFFBEB",
    yellow4: "#FEF3C7",
    yellow6: "#FDE68A",
    yellow7: "#FCD34D",
    yellow9: "#D79628",
    yellow10: "#D97706",
    yellow11: "#92400E",
  },
  dark: {
    ...generatedThemes.dark,
    background: fintPalette.dark.background,
    color: fintPalette.dark.text,
    card: fintPalette.dark.surface,
    cardForeground: fintPalette.dark.text,
    popover: fintPalette.dark.surface,
    popoverForeground: fintPalette.dark.text,
    primary: fintPalette.dark.action,
    primaryForeground: fintPalette.dark.background,
    primaryStrong: fintPalette.dark.actionPressed,
    portfolio: fintPalette.dark.action,
    portfolioForeground: fintPalette.dark.background,
    secondary: fintPalette.dark.subtle,
    secondaryForeground: fintPalette.dark.primaryStrong,
    muted: fintPalette.dark.subtle,
    mutedForeground: fintPalette.dark.muted,
    elevated: fintPalette.dark.elevated,
    accent: fintPalette.dark.action,
    accentForeground: fintPalette.dark.background,
    destructive: fintPalette.dark.dangerHard,
    success: fintPalette.dark.success,
    borderColor: fintPalette.dark.border,
    input: fintPalette.dark.border,
    ring: fintPalette.dark.action,
    accent8: fintPalette.dark.action,
    accent9: fintPalette.dark.action,
    accent10: fintPalette.dark.action,
    headerBackground: fintPalette.dark.headerBackground,
    headerBorder: fintPalette.dark.headerBorder,
    headerForeground: fintPalette.dark.headerText,
    headerMuted: fintPalette.dark.headerMuted,
    headerAccent: fintPalette.dark.headerAccent,
    tabBackground: fintPalette.dark.tabBackground,
    tabBorder: fintPalette.dark.tabBorder,
    tabActive: fintPalette.dark.tabActive,
    tabInactive: fintPalette.dark.tabInactive,
    tabFloatingBackground: fintPalette.dark.tabFloatingBackground,
    tabFloatingBorder: fintPalette.dark.tabFloatingBorder,
    tabPill: fintPalette.dark.tabPill,
    heroBackground: fintPalette.dark.heroBackground,
    heroBorder: fintPalette.dark.heroBorder,
    heroForeground: fintPalette.dark.groundForeground,
    heroMuted: fintPalette.dark.heroMuted,
    heroAccent: fintPalette.dark.groundAccent,
    // Sistema de diseño: los componentes nuevos de src/ui usan estas claves.
    canvas: fintPalette.dark.canvas,
    surface: fintPalette.dark.surface,
    surfaceSunken: fintPalette.dark.surfaceSunken,
    surfaceOverlay: fintPalette.dark.surfaceOverlay,
    segmentThumb: fintPalette.dark.segmentThumb,
    slab: fintPalette.dark.slab,
    slabLine: fintPalette.dark.slabLine,
    line: fintPalette.dark.line,
    lineStrong: fintPalette.dark.lineStrong,
    ink: fintPalette.dark.ink,
    inkMuted: fintPalette.dark.inkMuted,
    inkFaint: fintPalette.dark.inkFaint,
    slabInk: fintPalette.dark.slabInk,
    slabMuted: fintPalette.dark.slabMuted,
    brand: fintPalette.dark.brand,
    brandStrong: fintPalette.dark.brandStrong,
    brandWash: fintPalette.dark.brandWash,
    onBrand: fintPalette.dark.onBrand,
    focus: fintPalette.dark.focus,
    flowIn: fintPalette.dark.flowIn,
    flowOut: fintPalette.dark.flowOut,
    flowInSlab: fintPalette.dark.flowInSlab,
    flowOutSlab: fintPalette.dark.flowOutSlab,
    brandSlab: fintPalette.dark.brandSlab,
    heroGlow: fintPalette.dark.heroGlow,
    heroGlowSoft: fintPalette.dark.heroGlowSoft,
    glassSlab: fintPalette.dark.glassSlab,
    glassSlabLine: fintPalette.dark.glassSlabLine,
    dangerHard: fintPalette.dark.dangerHard,
    onDanger: fintPalette.dark.onDanger,
    signal: fintPalette.dark.signal,
    chartTrack: fintPalette.dark.chartTrack,
    scrim: fintPalette.dark.scrim,
    glass: fintPalette.dark.glass,
    glassLine: fintPalette.dark.glassLine,
    chart1: fintPalette.dark.chart[0],
    chart2: fintPalette.dark.chart[1],
    chart3: fintPalette.dark.chart[2],
    chart4: fintPalette.dark.chart[3],
    chart5: fintPalette.dark.chart[4],
    chart6: fintPalette.dark.chart[5],
    red2: fintPalette.dark.negativeTint,
    red3: fintPalette.dark.negativeTint,
    red4: "#512C2C",
    red5: "#643A3A",
    red6: fintPalette.dark.danger,
    red8: fintPalette.dark.danger,
    red9: fintPalette.dark.danger,
    red10: fintPalette.dark.danger,
    red11: fintPalette.dark.danger,
    green2: fintPalette.dark.positiveTint,
    green3: fintPalette.dark.positiveTint,
    green4: "#1B412A",
    green6: fintPalette.dark.success,
    green9: fintPalette.dark.success,
    green10: fintPalette.dark.success,
    green11: fintPalette.dark.success,
    // Sin estos, el oscuro cae al `yellowDark` de Tamagui: amarillos puros que
    // gritan sobre el fondo (el banner de pendientes, los montos "por revisar").
    yellow2: "#3B2F12",
    yellow4: "#54421A",
    yellow6: "#7A6027",
    yellow7: "#8F7130",
    yellow9: "#B07F1E",
    yellow10: "#E2B457",
    yellow11: "#F3D392",
  },
};

// Tracking específico por tamaño (principio apple-design): positivo y sutil en
// texto pequeño, cada vez más negativo a medida que crece.
const trackingBySize = {
  1: 0.02,
  2: 0.01,
  3: 0,
  4: -0.02,
  5: -0.03,
  6: -0.06,
  7: -0.09,
  8: -0.14,
  9: -0.22,
  10: -0.32,
  11: -0.36,
  12: -0.4,
};

const weightScale = { 1: "400", 4: "400", 5: "500", 6: "600", 7: "700", 8: "700", 9: "700" } as const;

/** Geist: cuerpo, etiquetas, botones y navegación. El 700 cae en SemiBold: sans vive en 400 y 600. */
const bodyFont = createSystemFont({
  font: {
    family: "Geist",
    face: {
      400: { normal: fontFace.sans[400] },
      500: { normal: fontFace.sans[500] },
      600: { normal: fontFace.sans[600] },
      700: { normal: fontFace.sans[600] },
    },
    weight: weightScale,
    letterSpacing: trackingBySize,
  },
});

/** Schibsted Grotesk: marca y títulos. Vive en 600; 400 y 500 también caen en SemiBold. */
const headingFont = createSystemFont({
  font: {
    family: "SchibstedGrotesk",
    face: {
      400: { normal: fontFace.display[600] },
      500: { normal: fontFace.display[600] },
      600: { normal: fontFace.display[600] },
      700: { normal: fontFace.display[700] },
    },
    weight: weightScale,
    letterSpacing: trackingBySize,
  },
});

/**
 * Geist Mono: toda cifra. Úsala como `fontFamily="$mono"` junto con
 * `fontVariant={["tabular-nums"]}`, o mejor con el componente `Amount`.
 */
const monoFont = createSystemFont({
  font: {
    family: "GeistMono",
    face: {
      400: { normal: fontFace.mono[400] },
      500: { normal: fontFace.mono[500] },
      600: { normal: fontFace.mono[600] },
      700: { normal: fontFace.mono[600] },
    },
    weight: weightScale,
    letterSpacing: trackingBySize,
  },
});

export const config = createTamagui({
  ...defaultConfig,
  animations,
  fonts: {
    ...defaultConfig.fonts,
    body: bodyFont,
    heading: headingFont,
    mono: monoFont,
  },
  themes,
});

export default config;

export type Conf = typeof config;

declare module "tamagui" {
  interface TamaguiCustomConfig extends Conf {}
}
