import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

interface CompactSkin {
  hexcode: string
  label: string
  unicode: string
}

interface CompactEmoji {
  hexcode: string
  label: string
  tags?: string[]
  unicode: string
  skins?: CompactSkin[]
}

const LOCALES = ['es', 'en', 'pt'] as const

async function loadLocale(locale: (typeof LOCALES)[number]): Promise<CompactEmoji[]> {
  try {
    const path = require.resolve(`emojibase-data/${locale}/compact.json`)
    const raw = await readFile(path, 'utf8')
    return JSON.parse(raw) as CompactEmoji[]
  } catch (error) {
    console.error(
      `\nCould not load emojibase-data/${locale}/compact.json.\n` +
        `Run "bun add -D emojibase-data" first, then re-run "bun run generate:emoji-index".\n`,
    )
    throw error
  }
}

const DIACRITICS_PATTERN = new RegExp(
  String.fromCharCode(0x5b, 0x5c, 0x75, 0x30, 0x33, 0x30, 0x30, 0x2d, 0x5c, 0x75, 0x30, 0x33, 0x36, 0x66, 0x5d),
  'g',
)

const STOPWORDS = new Set([
  'de', 'la', 'el', 'los', 'las', 'un', 'una', 'unos', 'unas', 'y', 'o', 'en', 'con', 'para', 'por', 'del', 'al', 'su', 'sus', 'que', 'es', 'son',
  'the', 'a', 'an', 'and', 'or', 'of', 'to', 'in', 'on', 'with', 'for', 'is', 'are',
  'da', 'do', 'das', 'dos', 'em', 'com', 'um', 'uma', 'uns', 'umas', 'e', 'ou', 'no', 'na', 'nos', 'nas', 'sao',
])

function normalizeKeyword(raw: string): string[] {
  const cleaned = raw.normalize('NFD').replace(DIACRITICS_PATTERN, '').toLowerCase().trim()
  return cleaned.split(/[^a-z0-9]+/).filter((word) => word.length >= 3 && !STOPWORDS.has(word))
}

const CATEGORY_CONCEPT_BOOST: Array<{ emoji: string; keywords: string[] }> = [
  { emoji: '💼', keywords: ['salario', 'sueldo', 'salary', 'nomina', 'payroll'] },
  { emoji: '💰', keywords: ['ahorro', 'ahorros', 'savings', 'poupanca'] },
  { emoji: '💳', keywords: ['deuda', 'deudas', 'debt', 'divida', 'prestamo', 'emprestimo', 'credito', 'credit', 'loan', 'cuota'] },
  { emoji: '🧾', keywords: ['factura', 'facturas', 'bill', 'impuesto', 'impuestos', 'tax', 'taxes', 'tributo', 'imposto'] },
  { emoji: '🛡️', keywords: ['seguro', 'seguros', 'insurance', 'poliza', 'seguranca'] },
  { emoji: '📈', keywords: ['inversion', 'inversiones', 'investment', 'investimento', 'acciones', 'stocks', 'bolsa'] },
  { emoji: '🏠', keywords: ['alquiler', 'arriendo', 'renta', 'aluguel', 'rent', 'vivienda', 'moradia', 'housing'] },
  { emoji: '🏋️', keywords: ['gimnasio', 'academia'] },
  { emoji: '🧑‍💻', keywords: ['freelance', 'independiente', 'autonomo', 'emprendimiento', 'consultoria'] },
  { emoji: '🏦', keywords: ['comision', 'comisiones', 'tarifa', 'tarifas', 'banco'] },
  { emoji: '🍽️', keywords: ['alimentacion', 'alimentacao', 'comida', 'food', 'alimento'] },
  { emoji: '🎓', keywords: ['educacion', 'educacao', 'escuela', 'escola', 'colegio'] },
  { emoji: '💡', keywords: ['utilities', 'servicios', 'servicos'] },
]

async function main() {
  const perLocale = await Promise.all(LOCALES.map(loadLocale))

  // hexcode -> { emoji glyph, merged/deduped keyword set }
  const merged = new Map<string, { emoji: string; keywords: Set<string> }>()

  for (const entries of perLocale) {
    for (const entry of entries) {
      const existing = merged.get(entry.hexcode)
      const bucket = existing ?? { emoji: entry.unicode, keywords: new Set<string>() }
      for (const word of normalizeKeyword(entry.label)) bucket.keywords.add(word)
      for (const tag of entry.tags ?? []) {
        for (const word of normalizeKeyword(tag)) bucket.keywords.add(word)
      }
      if (!existing) merged.set(entry.hexcode, bucket)
    }
  }

  const stripVariationSelector = (glyph: string) => glyph.replace(/️$/, '')
  const byEmoji = new Map(Array.from(merged.values()).map((bucket) => [stripVariationSelector(bucket.emoji), bucket]))
  for (const boost of CATEGORY_CONCEPT_BOOST) {
    const bucket = byEmoji.get(stripVariationSelector(boost.emoji))
    if (!bucket) throw new Error(`CATEGORY_CONCEPT_BOOST references an emoji not found in the base index: ${boost.emoji}`)
    for (const keyword of boost.keywords) bucket.keywords.add(keyword)
  }

  const output = Array.from(merged.values())
    .filter((bucket) => bucket.keywords.size > 0)
    .map((bucket) => ({ e: bucket.emoji, k: Array.from(bucket.keywords).sort() }))

  const banner =
    '// AUTO-GENERATED by scripts/generate-emoji-index.ts -- do not edit by hand.\n' +
    '// Regenerate with: bun run generate:emoji-index\n' +
    `// Source: emojibase-data (${LOCALES.join('/')} locales), compact.json, skin-tone variants excluded.\n\n`

  const body =
    'export interface EmojiIndexEntry {\n' +
    '  e: string\n' +
    '  k: string[]\n' +
    '}\n\n' +
    `export const emojiIndex: EmojiIndexEntry[] = ${JSON.stringify(output)}\n`

  const outDir = join(import.meta.dir, '..', 'src', 'finance')
  const outPath = join(outDir, 'emojiIndex.generated.ts')
  await mkdir(outDir, { recursive: true })
  await writeFile(outPath, banner + body)

  console.log(`Wrote ${output.length} emoji entries to src/finance/emojiIndex.generated.ts`)
}

await main()
